"use strict";

/* ==========================================================================
   5b. Sound
   --------------------------------------------------------------------------
   Everything here is generated by the browser: filtered noise for the road and
   the wind, an oscillator for the drivetrain, a procedurally built impulse
   response for the tunnel reverb, and short FM blips for birds. No audio
   files, so the page stays one self-contained thing that works offline.
   ========================================================================== */

const AU={ctx:null,ready:false,n:null,birdAt:0,thunkAt:0,tickAt:0};

function audioStart(){
  if(AU.ctx){ if(AU.ctx.state==='suspended') AU.ctx.resume(); return; }
  const C=window.AudioContext||window.webkitAudioContext;
  if(!C) return;
  let ctx;
  try{ ctx=new C(); }catch(e){ return; }
  AU.ctx=ctx;

  const master=ctx.createGain(); master.gain.value=0; master.connect(ctx.destination);

  /* two seconds of soft (pink-ish) noise, reused everywhere */
  const len=Math.floor(ctx.sampleRate*2);
  const buf=ctx.createBuffer(1,len,ctx.sampleRate);
  const d=buf.getChannelData(0);
  let last=0;
  for(let i=0;i<len;i++){ const w=Math.random()*2-1; last=(last+0.02*w)/1.02; d[i]=last*3.2; }
  const noise=()=>{const s=ctx.createBufferSource();s.buffer=buf;s.loop=true;s.start();return s;};

  /* a dry path and a reverberant one, crossfaded when you go underground */
  const dry=ctx.createGain(); dry.gain.value=1;
  const wet=ctx.createGain(); wet.gain.value=0;
  const conv=ctx.createConvolver();
  const rn=Math.floor(ctx.sampleRate*1.7), rb=ctx.createBuffer(2,rn,ctx.sampleRate);
  for(let c=0;c<2;c++){
    const ch=rb.getChannelData(c);
    for(let i=0;i<rn;i++) ch[i]=(Math.random()*2-1)*Math.pow(1-i/rn,2.5);
  }
  conv.buffer=rb;
  dry.connect(master); wet.connect(conv); conv.connect(master);
  const bus=ctx.createGain(); bus.connect(dry); bus.connect(wet);

  /* Tyres on tarmac. This is a hiss, not a rumble: low-frequency noise down
     around 200 Hz is what an engine sounds like, so everything continuous is
     kept well above it. The only low end in the whole mix is the bridge boom,
     and that is silent unless you are on a bridge. */
  const roadS=noise();
  const roadF=ctx.createBiquadFilter(); roadF.type='bandpass';
  roadF.frequency.value=900; roadF.Q.value=0.7;
  const roadG=ctx.createGain(); roadG.gain.value=0;
  roadS.connect(roadF); roadF.connect(roadG); roadG.connect(bus);

  /* hollow boom under a bridge deck — the one deliberately low layer */
  const boomS=noise();
  const boomF=ctx.createBiquadFilter(); boomF.type='lowpass'; boomF.frequency.value=110;
  const boomG=ctx.createGain(); boomG.gain.value=0;
  boomS.connect(boomF); boomF.connect(boomG); boomG.connect(bus);

  /* wind past your ears — only on worlds with air */
  const windS=noise();
  const windF=ctx.createBiquadFilter(); windF.type='bandpass';
  windF.frequency.value=700; windF.Q.value=0.55;
  const windG=ctx.createGain(); windG.gain.value=0;
  windS.connect(windF); windF.connect(windG); windG.connect(bus);

  /* Drivetrain. A bike does not drone — the chain rustles over the cogs, so
     this is filtered noise, never an oscillator. An oscillator here is how you
     build an engine, which is exactly what it sounded like. */
  const chainS=noise();
  const chainF=ctx.createBiquadFilter(); chainF.type='bandpass';
  chainF.frequency.value=1900; chainF.Q.value=1.1;
  const chainG=ctx.createGain(); chainG.gain.value=0;
  chainS.connect(chainF); chainF.connect(chainG); chainG.connect(bus);

  /* the stroke itself: one push per leg, so twice per crank revolution. It
     swells the chain noise rather than adding a note of its own. */
  const lfo=ctx.createOscillator(); lfo.type='sine'; lfo.frequency.value=2.8;
  const lfoG=ctx.createGain(); lfoG.gain.value=0;
  lfo.connect(lfoG); lfoG.connect(chainG.gain); lfo.start();

  /* flywheel: the soft whoosh a trainer makes, following speed */
  const flyS=noise();
  const flyF=ctx.createBiquadFilter(); flyF.type='bandpass';
  flyF.frequency.value=420; flyF.Q.value=0.9;
  const flyG=ctx.createGain(); flyG.gain.value=0;
  flyS.connect(flyF); flyF.connect(flyG); flyG.connect(bus);

  AU.n={master,bus,dry,wet,roadF,roadG,windF,windG,chainF,chainG,lfo,lfoG,flyF,flyG,boomG};
  AU.ready=true;
}

/* one short sound, used for birdsong and for the thump of bridge joints */
function blip(kind){
  if(!AU.ready) return;
  const ctx=AU.ctx,t=ctx.currentTime;
  const o=ctx.createOscillator(), g=ctx.createGain();
  if(kind==='bird'){
    o.type='sine';
    const f=1700+Math.random()*2300;
    o.frequency.setValueAtTime(f,t);
    o.frequency.exponentialRampToValueAtTime(f*(0.55+Math.random()*0.95),t+0.09);
    g.gain.setValueAtTime(0.0001,t);
    g.gain.linearRampToValueAtTime(0.05+Math.random()*0.05,t+0.012);
    g.gain.exponentialRampToValueAtTime(0.0001,t+0.17);
    o.start(t); o.stop(t+0.2);
  }else if(kind==='tick'){        /* freehub pawl, heard when you coast */
    o.type='square';
    o.frequency.setValueAtTime(2500+Math.random()*500,t);
    g.gain.setValueAtTime(0.0001,t);
    g.gain.linearRampToValueAtTime(0.022,t+0.002);
    g.gain.exponentialRampToValueAtTime(0.0001,t+0.03);
    o.start(t); o.stop(t+0.045);
  }else{
    o.type='triangle';
    o.frequency.setValueAtTime(120,t);
    o.frequency.exponentialRampToValueAtTime(48,t+0.13);
    g.gain.setValueAtTime(0.0001,t);
    g.gain.linearRampToValueAtTime(0.16,t+0.006);
    g.gain.exponentialRampToValueAtTime(0.0001,t+0.2);
    o.start(t); o.stop(t+0.22);
  }
  o.connect(g); g.connect(AU.n.bus);
}

function audioTick(){
  if(!AU.ready) return;
  const n=AU.n, t=AU.ctx.currentTime, k=0.14;
  const set=(p,v)=>{ try{p.setTargetAtTime(v,t,k);}catch(e){p.value=v;} };

  const live=cfg.sound && state.running;
  set(n.master.gain, live?cfg.vol:0);
  if(!live) return;

  const A=(state.scene&&state.scene.audio)||{wind:0.5,birds:0};
  const spN=clamp(state.speed/16,0,1.5);

  let inT=0,inB=0;
  if(world&&world.inTunnel){
    const i=segIdx(state.seg,state.s);
    inT=world.inTunnel[i]; inB=world.inBridge[i];
  }

  set(n.roadG.gain, (0.02+0.17*spN)*(inT?1.3:1));
  set(n.roadF.frequency, 700+1300*spN);
  set(n.windG.gain, (A.wind||0)*(0.015+0.55*Math.pow(spN,1.7))*(inT?0.35:1));
  set(n.windF.frequency, 480+1500*spN);
  /* chain rustle, swelling once per crank revolution so the rhythm you hear
     is your cadence exactly: 85 rpm -> 1.42 swells a second */
  const pedalling=state.cad>8;
  set(n.lfo.frequency, Math.max(0.25, state.cad/60));
  set(n.chainG.gain, pedalling?0.085:0);
  set(n.lfoG.gain,   pedalling?0.065:0);
  set(n.chainF.frequency, 1500+state.cad*7);
  set(n.flyG.gain, 0.015+0.06*spN);
  set(n.flyF.frequency, 600+900*spN);
  set(n.boomG.gain, inB?0.11:0);
  /* underground: the dry sound drops back and the room takes over */
  set(n.dry.gain, inT?0.4:1);
  set(n.wet.gain, inT?0.9:0.03);

  const now=AU.ctx.currentTime;
  if((A.birds||0)>0 && !inT && now>AU.birdAt){
    AU.birdAt=now+0.5+Math.random()*(4.5/(A.birds||1));
    blip('bird');
  }
  /* coasting: the freewheel ticks away, faster the quicker you are going */
  if(!pedalling && state.speed>1.5 && now>AU.tickAt){
    AU.tickAt=now+clamp(0.55/state.speed,0.045,0.4);
    blip('tick');
  }
  /* expansion joints going by on a bridge deck */
  if(inB && state.speed>2 && now>AU.thunkAt){
    AU.thunkAt=now+Math.max(0.35, 26/Math.max(state.speed,2));
    blip('thunk');
  }
}

/* Silence as soon as the page is hidden. The animation loop is throttled or
   stopped when a tab goes to the background, so without this the last gain
   values would simply keep sounding. */
document.addEventListener('visibilitychange',function(){
  if(!AU.ctx) return;
  if(document.hidden){
    try{ AU.n.master.gain.value=0; AU.ctx.suspend(); }catch(e){}
  }else if(cfg.sound){
    try{ AU.ctx.resume(); }catch(e){}
  }
});
addEventListener('pagehide',function(){ try{ AU.ctx&&AU.ctx.close(); }catch(e){} });

